---
# This playbook prints a simple debug message
- hosts: all
  become: yes

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!

  #- name: Run apt-get update
  #  apt:
  #    update_cache: yes

  - name: Install Packages
    apt: 
      name: 
        - apache2
      state: present
    

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: ./files/index.html
      dest: /home/vagrant
      